services:
  - type: web
    name: billing-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    pythonVersion: 3.11
    region: oregon
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://shivanshink:j2TdbmLYKhG7r5us@billing-app.u8vogax.mongodb.net/billing-app?retryWrites=true&w=majority&appName=billing-app
