services:
  - type: web
    name: billing-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    pythonVersion: 3.11
    region: oregon
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://akshad:<db_password>@cluster1.azieu0u.mongodb.net/?retryWrites=true&w=majority&appName=cluster1
